# Generated by Django 4.1.6 on 2023-02-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='addres',
            new_name='address',
        ),
    ]
