# Generated by Django 4.1.6 on 2023-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_addres_provider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(default=1, upload_to='providers', verbose_name='image'),
            preserve_default=False,
        ),
    ]
